### PR TITLE
moving directory due to app name length

### PR DESCRIPTION
**Pull request by jhsinger-klotho**
renaming the dir so that the tests will pass. They fail due to resource name length which includes the app name (derived from directory name).

Since this is a temp sample app until we have a way to test multiple configs, just changing directory name

### CODE REVIEW

**Review by gordon-klotho — APPROVED** [review]
I would prefer we solve this by properly abbreviating in `klotho`, but I suppose this will suffice for now.

**Comment by DavidSeptimus-Klotho** [comment]
A change like this should also include corresponding changes in the README and docs.

**Comment by jhsinger-klotho** [comment]
ah yeah i can update the readme. I agree i dont like this and moved the cards to solve this in klotho to prioritized so we can delete this app altogether. But i do think its critical to have this being tested which is why i wanted to get it in for now.

**Comment by jhsinger-klotho** [comment]
> It's also referenced in the Key Value Stores use case: https://klo.dev/docs/tutorials/use_cases/key_value

yeah the regular ts-microservices is unchanged, this is purely to cover a testing gap so we have a clone

**Pull request merged**
